auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: conc's Blog conc的博客
url: https://conc.github.io/
feed: /atom.xml
author_info: <a href="https://conc.github.io/">Looly</a>
